import { bangers, nunito } from "@/fonts";
import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

interface RootLayoutProps {
  children: ReactNode;
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${bangers.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
